### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by chesterbr** [chesterbr/minitruco-android#19]
In #18, @TodorBalabanov kindly collected the un-resourced strings and introduced an English resource file, which needs revision from someone that understands English and Portuguese well - but once done, we can have the game in English (and follow with other languages, why not? 😄).

**Comment by TodorBalabanov** [comment]
Yes. It is better someone with good English to check the translation.

**Comment by chesterbr** [comment]
Unfortunately I could not check the translations at the time (wasn't really maintaining miniTruco until the last couple months), and some structural changes came (and will come) that will require a full overhaul on this.

Since I haven't heard a lot about people from other countries playing truco (other than Argentina, which plays with a different set of cards and rules), I will not pursue this for now, but happy to revisit in the future once the dust settles a bit.
