### ISSUE TITLE
"parceiro" aceita truco perdido

### ISSUE THREAD

**Issue by daniloprates** [chesterbr/minitruco-android#5]
Não sei se aqui é o melhor local pra esse tipo de feedback. O jogo é demais, estou viciado. Porém, em várias ocasiões o "parceiro" aceitou truco claramente perdido, que nem era caso pra blefe.

O ideal seria uma polida nessa lógica ou até mesmo uma opção de desabilitar que o parceiro aceite (ou até mesmo peça) truco.

**Comment by chesterbr** [comment]
Danilo, agora o parceiro não pode aceitar truco em nome da dupla com humano (a não ser que a opção correspondente seja desligada), então este problema está resolvido.
