### ISSUE TITLE
Adicionar ao F-Droid

### ISSUE THREAD

**Issue by pizzamaker** [chesterbr/minitruco-android#7]
Seria muito bacana ter esse app no F-Droid, que é uma espécie de Google Play mas com apenas software livre: https://f-droid.org/

Aqui tem instruções de como adicioná-lo à fila de inclusão: https://f-droid.org/contribute/

**Comment by chesterbr** [comment]
Olá @pizzamaker. Obrigado pela sugestão, o F-Droid parece ser realmente uma idéia interessante. Eu não tenho como manter o aplicativo em outras app stores (mal tenho conseguido manter ele no geral), mas não tenho nada contra (e nem a licença impede) se alguém quiser adicionar ele ao F-Droid.
